package apperror

import (
	"errors"
)

var (
	ErrInternalServer                    = errors.New("the server encounter error, please try again later")
	ErrResourceNotFound                  = errors.New("resource is not found")
	ErrInvalidRequest                    = errors.New("payload is invalid")
	ErrInvalidCredential                 = errors.New("email or password is incorrect")
	ErrInvalidEmail                      = errors.New("email is invalid")
	ErrInvalidToken                      = errors.New("token is invalid")
	ErrInvalidPassword                   = errors.New("password is incorrect")
	ErrInvalidPassToken                  = errors.New("password or token combination is incorrect")
	ErrInvalidParam                      = errors.New("route param is invalid")
	ErrUnauthorized                      = errors.New("unauthorized")
	ErrDrugExist                         = errors.New("cannot add a drug because the drug exists")
	ErrPharmacyDrugNotExist              = errors.New("the drug is not exist in this pharmacy")
	ErrPharmacyDrugCantEdit              = errors.New("cannot update quantity the prescripted drug")
	ErrEmailExist                        = errors.New("the email has been already registered")
	ErrEmailCantResetPassword            = errors.New("this email cannot do forgot and reset password")
	ErrHasBeenVerified                   = errors.New("this email has been verified")
	ErrFileTooLarge                      = errors.New("file size too large")
	ErrFileInvalidType                   = errors.New("invalid file type")
	ErrMustMainAddress                   = errors.New("this address must be set as main address")
	ErrSubdistrictNotAvail               = errors.New("the subdistrict is not available")
	ErrMainMustActiveAddress             = errors.New("main address must set as active")
	ErrCantDeleteMainAddress             = errors.New("cannot delete main address")
	ErrPrescriptedExist                  = errors.New("cannot add because this prescripted is exists")
	ErrInsufficientStock                 = errors.New("cannot add because stock is insufficient")
	ErrNoValidCartInsideOrder            = errors.New("there's no valid cart inside the order, cannot make a payment")
	ErrInvalidIdParams                   = errors.New("id params must greater then 0")
	ErrDoctorNotExist                    = errors.New("the doctor is not exist")
	ErrNoValidOrder                      = errors.New("no valid order, can't update")
	ErrNoValidPayment                    = errors.New("no valid payment")
	ErrInsufficientStockMutation         = errors.New("cannot process because stock is insufficient in all pharmacies")
	ErrAddressNotExist                   = errors.New("the address is not exist")
	ErrRajaOngkirEncountered             = errors.New("something error when using raja ongkir API")
	ErrShipmentMethodInvalid             = errors.New("shipment methods doesn't appear on pharmacy")
	ErrTelemedicineHasBeenEnded          = errors.New("telemedicine has been ended")
	ErrTelemedicineOngoingWithDoctor     = errors.New("still doing telemedicine with this doctor")
	ErrCategoryNameExist                 = errors.New("the category name is exist")
	ErrCantCancelOrder                   = errors.New("cannot cancel the order")
	ErrCantRequestToSamePharmacy         = errors.New("cannot request to the same pharmacy")
	ErrCantRequestToPharmaciesNotPartner = errors.New("cannot request to the pharmacies which is not partner")
	ErrPharmacyDrugExist                 = errors.New("the drugs is exist in the pharmacy")
	ErrDrugNotExist                      = errors.New("the drug is not exist")
	ErrPharmacyNotExist                  = errors.New("the pharmacy is not exist")
	ErrCategoryNotExist                  = errors.New("the category is not exist")
	ErrEmailOAuthNotFound                = errors.New("email with google is not found, register it first")
	ErrSenderAndReceiverCantSame         = errors.New("sender and receiver must be different")
	ErrStockMutationCancel               = errors.New("cannot cancel stock mutation")
	ErrStockMutationApprove              = errors.New("cannot approve stock mutation")
	ErrCantDeleteCategory                = errors.New("cannot delete the category because linked pharmacy drug is exist")
)

var (
	ErrAssertingAny = errors.New("cannot asserting")
	ErrNoRoute      = errors.New("route is not found")
)
